<?xml version="1.0"?>
<package format="3">
  <name>omni_robot_bringup</name>
  <version>0.0.1</version>
  <description>Bringup package for 4-wheel omni robot</description>

  <maintainer email="your_email@iiti.ac.in">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend> <exec_depend>controller_manager</exec_depend>

  <exec_depend>omni_wheel_controller</exec_depend>
  <exec_depend>your_actual_hardware_package_name</exec_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend> <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
